name: Preview Website

on: [pull_request]

jobs:
  preview:
    name: Preview at Firebase
    runs-on: ubuntu-latest
    steps:      
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'
     
      - name: Install packages
        run: npm install
        
      - name: Build Static Files
        run: npm run export
      
      - name: Install Firebase
        run: npm install -g firebase-tools
     
      - name: Create Channel
        run: firebase hosting:channel:create ${{ github.event.number }} --token=${{secrets.FIREBASE_TOKEN}}
        
      - name: Deploy Channel
        run: firebase hosting:channel:deploy ${{ github.event.number }} --token=${{secrets.FIREBASE_TOKEN}}

      - name: Comment with URL
        env:
          URL: ${{ github.event.pull_request.comments_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        run: |
           MESSAGE=$(firebase hosting:channel:open ${{ github.event.number }} --token=${{secrets.FIREBASE_TOKEN}}) && curl \
            -X POST \
            $URL \
            -H "Content-Type: application/json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            --data '{ "body": "$MESSAGE" }'
